// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataUpdateMethods.Models;

[Table("BuyingGroups", Schema = "Sales")]
[Index("BuyingGroupName", Name = "UQ_Sales_BuyingGroups_BuyingGroupName", IsUnique = true)]
public partial class BuyingGroup
{
    [Key]
    [Column("BuyingGroupID")]
    public int BuyingGroupId { get; set; }

    [Required]
    [StringLength(50)]
    public string BuyingGroupName { get; set; }

    public int LastEditedBy { get; set; }

    [InverseProperty("BuyingGroup")]
    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    [ForeignKey("LastEditedBy")]
    [InverseProperty("BuyingGroups")]
    public virtual Person LastEditedByNavigation { get; set; }

    [InverseProperty("BuyingGroup")]
    public virtual ICollection<SpecialDeal> SpecialDeals { get; set; } = new List<SpecialDeal>();
}