// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataUpdateMethods.Models;

[Table("Cities", Schema = "Application")]
[Index("StateProvinceId", Name = "FK_Application_Cities_StateProvinceID")]
public partial class City
{
    [Key]
    [Column("CityID")]
    public int CityId { get; set; }

    [Required]
    [StringLength(50)]
    public string CityName { get; set; }

    [Column("StateProvinceID")]
    public int StateProvinceId { get; set; }

    public long? LatestRecordedPopulation { get; set; }

    public int LastEditedBy { get; set; }

    [InverseProperty("DeliveryCity")]
    public virtual ICollection<Customer> CustomerDeliveryCities { get; set; } = new List<Customer>();

    [InverseProperty("PostalCity")]
    public virtual ICollection<Customer> CustomerPostalCities { get; set; } = new List<Customer>();

    [ForeignKey("LastEditedBy")]
    [InverseProperty("Cities")]
    public virtual Person LastEditedByNavigation { get; set; }

    [ForeignKey("StateProvinceId")]
    [InverseProperty("Cities")]
    public virtual StateProvince StateProvince { get; set; }

    [InverseProperty("DeliveryCity")]
    public virtual ICollection<Supplier> SupplierDeliveryCities { get; set; } = new List<Supplier>();

    [InverseProperty("PostalCity")]
    public virtual ICollection<Supplier> SupplierPostalCities { get; set; } = new List<Supplier>();

    [InverseProperty("DeliveryCity")]
    public virtual ICollection<SystemParameter> SystemParameterDeliveryCities { get; set; } = new List<SystemParameter>();

    [InverseProperty("PostalCity")]
    public virtual ICollection<SystemParameter> SystemParameterPostalCities { get; set; } = new List<SystemParameter>();
}