// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataUpdateMethods.Models;

[Table("ColdRoomTemperatures", Schema = "Warehouse")]
[Index("ColdRoomSensorNumber", Name = "IX_Warehouse_ColdRoomTemperatures_ColdRoomSensorNumber")]
public partial class ColdRoomTemperature
{
    [Key]
    [Column("ColdRoomTemperatureID")]
    public long ColdRoomTemperatureId { get; set; }

    public int ColdRoomSensorNumber { get; set; }

    public DateTime RecordedWhen { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Temperature { get; set; }
}