// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataUpdateMethods.Models;

[Table("Colors", Schema = "Warehouse")]
[Index("ColorName", Name = "UQ_Warehouse_Colors_ColorName", IsUnique = true)]
public partial class Color
{
    [Key]
    [Column("ColorID")]
    public int ColorId { get; set; }

    [Required]
    [StringLength(20)]
    public string ColorName { get; set; }

    public int LastEditedBy { get; set; }

    [ForeignKey("LastEditedBy")]
    [InverseProperty("Colors")]
    public virtual Person LastEditedByNavigation { get; set; }

    [InverseProperty("Color")]
    public virtual ICollection<StockItem> StockItems { get; set; } = new List<StockItem>();
}