// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataUpdateMethods.Models;

/// <summary>
/// Represents a country in the application schema.
/// </summary>
[Table("Countries", Schema = "Application")]
[Index("CountryName", Name = "UQ_Application_Countries_CountryName", IsUnique = true)]
[Index("FormalName", Name = "UQ_Application_Countries_FormalName", IsUnique = true)]
public partial class Country
{
    [Key]
    [Column("CountryID")]
    public int CountryId { get; set; }

    [Required]
    [StringLength(60)]
    public string CountryName { get; set; }

    [Required]
    [StringLength(60)]
    public string FormalName { get; set; }

    [StringLength(3)]
    public string IsoAlpha3Code { get; set; }

    public int? IsoNumericCode { get; set; }

    [StringLength(20)]
    public string CountryType { get; set; }

    public long? LatestRecordedPopulation { get; set; }

    [Required]
    [StringLength(30)]
    public string Continent { get; set; }

    [Required]
    [StringLength(30)]
    public string Region { get; set; }

    [Required]
    [StringLength(30)]
    public string Subregion { get; set; }

    public int LastEditedBy { get; set; }

    [ForeignKey("LastEditedBy")]
    [InverseProperty("Countries")]
    public virtual Person LastEditedByNavigation { get; set; }

    [InverseProperty("Country")]
    public virtual ICollection<StateProvince> StateProvinces { get; set; } = new List<StateProvince>();
}
