// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataUpdateMethods.Models;

[Table("DeliveryMethods", Schema = "Application")]
[Index("DeliveryMethodName", Name = "UQ_Application_DeliveryMethods_DeliveryMethodName", IsUnique = true)]
public partial class DeliveryMethod
{
    [Key]
    [Column("DeliveryMethodID")]
    public int DeliveryMethodId { get; set; }

    [Required]
    [StringLength(50)]
    public string DeliveryMethodName { get; set; }

    public int LastEditedBy { get; set; }

    [InverseProperty("DeliveryMethod")]
    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    [InverseProperty("DeliveryMethod")]
    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    [ForeignKey("LastEditedBy")]
    [InverseProperty("DeliveryMethods")]
    public virtual Person LastEditedByNavigation { get; set; }

    [InverseProperty("DeliveryMethod")]
    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; } = new List<PurchaseOrder>();

    [InverseProperty("DeliveryMethod")]
    public virtual ICollection<Supplier> Suppliers { get; set; } = new List<Supplier>();
}