// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataUpdateMethods.Models;

[Table("OrderLines", Schema = "Sales")]
[Index("OrderId", Name = "FK_Sales_OrderLines_OrderID")]
[Index("PackageTypeId", Name = "FK_Sales_OrderLines_PackageTypeID")]
[Index("StockItemId", Name = "IX_Sales_OrderLines_AllocatedStockItems")]
[Index("PickingCompletedWhen", "OrderId", "OrderLineId", Name = "IX_Sales_OrderLines_Perf_20160301_01")]
[Index("StockItemId", "PickingCompletedWhen", Name = "IX_Sales_OrderLines_Perf_20160301_02")]
public partial class OrderLine
{
    [Key]
    [Column("OrderLineID")]
    public int OrderLineId { get; set; }

    [Column("OrderID")]
    public int OrderId { get; set; }

    [Column("StockItemID")]
    public int StockItemId { get; set; }

    [Required]
    [StringLength(100)]
    public string Description { get; set; }

    [Column("PackageTypeID")]
    public int PackageTypeId { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? UnitPrice { get; set; }

    [Column(TypeName = "decimal(18, 3)")]
    public decimal TaxRate { get; set; }

    public int PickedQuantity { get; set; }

    public DateTime? PickingCompletedWhen { get; set; }

    public int LastEditedBy { get; set; }

    public DateTime LastEditedWhen { get; set; }

    [ForeignKey("LastEditedBy")]
    [InverseProperty("OrderLines")]
    public virtual Person LastEditedByNavigation { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderLines")]
    public virtual Order Order { get; set; }

    [ForeignKey("PackageTypeId")]
    [InverseProperty("OrderLines")]
    public virtual PackageType PackageType { get; set; }

    [ForeignKey("StockItemId")]
    [InverseProperty("OrderLines")]
    public virtual StockItem StockItem { get; set; }
}