// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataUpdateMethods.Models;

[Table("PackageTypes", Schema = "Warehouse")]
[Index("PackageTypeName", Name = "UQ_Warehouse_PackageTypes_PackageTypeName", IsUnique = true)]
public partial class PackageType
{
    [Key]
    [Column("PackageTypeID")]
    public int PackageTypeId { get; set; }

    [Required]
    [StringLength(50)]
    public string PackageTypeName { get; set; }

    public int LastEditedBy { get; set; }

    [InverseProperty("PackageType")]
    public virtual ICollection<InvoiceLine> InvoiceLines { get; set; } = new List<InvoiceLine>();

    [ForeignKey("LastEditedBy")]
    [InverseProperty("PackageTypes")]
    public virtual Person LastEditedByNavigation { get; set; }

    [InverseProperty("PackageType")]
    public virtual ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();

    [InverseProperty("PackageType")]
    public virtual ICollection<PurchaseOrderLine> PurchaseOrderLines { get; set; } = new List<PurchaseOrderLine>();

    [InverseProperty("OuterPackage")]
    public virtual ICollection<StockItem> StockItemOuterPackages { get; set; } = new List<StockItem>();

    [InverseProperty("UnitPackage")]
    public virtual ICollection<StockItem> StockItemUnitPackages { get; set; } = new List<StockItem>();
}