// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataUpdateMethods.Models;

/// <summary>
/// Represents a purchase order in the purchasing schema.
/// </summary>
[Table("PurchaseOrders", Schema = "Purchasing")]
[Index("ContactPersonId", Name = "FK_Purchasing_PurchaseOrders_ContactPersonID")]
[Index("DeliveryMethodId", Name = "FK_Purchasing_PurchaseOrders_DeliveryMethodID")]
[Index("SupplierId", Name = "FK_Purchasing_PurchaseOrders_SupplierID")]
public partial class PurchaseOrder
{
    [Key]
    [Column("PurchaseOrderID")]
    public int PurchaseOrderId { get; set; }

    [Column("SupplierID")]
    public int SupplierId { get; set; }

    [Column(TypeName = "date")]
    public DateTime OrderDate { get; set; }

    [Column("DeliveryMethodID")]
    public int DeliveryMethodId { get; set; }

    [Column("ContactPersonID")]
    public int ContactPersonId { get; set; }

    [Column(TypeName = "date")]
    public DateTime? ExpectedDeliveryDate { get; set; }

    [StringLength(20)]
    public string SupplierReference { get; set; }

    public bool IsOrderFinalized { get; set; }

    public string Comments { get; set; }

    public string InternalComments { get; set; }

    public int LastEditedBy { get; set; }

    public DateTime LastEditedWhen { get; set; }

    [ForeignKey("ContactPersonId")]
    [InverseProperty("PurchaseOrderContactPeople")]
    public virtual Person ContactPerson { get; set; }

    [ForeignKey("DeliveryMethodId")]
    [InverseProperty("PurchaseOrders")]
    public virtual DeliveryMethod DeliveryMethod { get; set; }

    [ForeignKey("LastEditedBy")]
    [InverseProperty("PurchaseOrderLastEditedByNavigations")]
    public virtual Person LastEditedByNavigation { get; set; }

    [InverseProperty("PurchaseOrder")]
    public virtual ICollection<PurchaseOrderLine> PurchaseOrderLines { get; set; } = new List<PurchaseOrderLine>();

    [InverseProperty("PurchaseOrder")]
    public virtual ICollection<StockItemTransaction> StockItemTransactions { get; set; } = new List<StockItemTransaction>();

    [ForeignKey("SupplierId")]
    [InverseProperty("PurchaseOrders")]
    public virtual Supplier Supplier { get; set; }

    [InverseProperty("PurchaseOrder")]
    public virtual ICollection<SupplierTransaction> SupplierTransactions { get; set; } = new List<SupplierTransaction>();
}
