// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataUpdateMethods.Models;

/// <summary>
/// Represents a stock item in the warehouse schema.
/// </summary>
[Table("StockItems", Schema = "Warehouse")]
[Index("ColorId", Name = "FK_Warehouse_StockItems_ColorID")]
[Index("OuterPackageId", Name = "FK_Warehouse_StockItems_OuterPackageID")]
[Index("SupplierId", Name = "FK_Warehouse_StockItems_SupplierID")]
[Index("UnitPackageId", Name = "FK_Warehouse_StockItems_UnitPackageID")]
[Index("StockItemName", Name = "UQ_Warehouse_StockItems_StockItemName", IsUnique = true)]
public partial class StockItem
{
    [Key]
    [Column("StockItemID")]
    public int StockItemId { get; set; }

    [Required]
    [StringLength(100)]
    public string StockItemName { get; set; }

    [Column("SupplierID")]
    public int SupplierId { get; set; }

    [Column("ColorID")]
    public int? ColorId { get; set; }

    [Column("UnitPackageID")]
    public int UnitPackageId { get; set; }

    [Column("OuterPackageID")]
    public int OuterPackageId { get; set; }

    [StringLength(50)]
    public string Brand { get; set; }

    [StringLength(20)]
    public string Size { get; set; }

    public int LeadTimeDays { get; set; }

    public int QuantityPerOuter { get; set; }

    public bool IsChillerStock { get; set; }

    [StringLength(50)]
    public string Barcode { get; set; }

    [Column(TypeName = "decimal(18, 3)")]
    public decimal TaxRate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal UnitPrice { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? RecommendedRetailPrice { get; set; }

    [Column(TypeName = "decimal(18, 3)")]
    public decimal TypicalWeightPerUnit { get; set; }

    public string MarketingComments { get; set; }

    public string InternalComments { get; set; }

    public byte[] Photo { get; set; }

    public string CustomFields { get; set; }

    public string Tags { get; set; }

    [Required]
    public string SearchDetails { get; set; }

    public int LastEditedBy { get; set; }

    [ForeignKey("ColorId")]
    [InverseProperty("StockItems")]
    public virtual Color Color { get; set; }

    [InverseProperty("StockItem")]
    public virtual ICollection<InvoiceLine> InvoiceLines { get; set; } = new List<InvoiceLine>();

    [ForeignKey("LastEditedBy")]
    [InverseProperty("StockItems")]
    public virtual Person LastEditedByNavigation { get; set; }

    [InverseProperty("StockItem")]
    public virtual ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();

    [ForeignKey("OuterPackageId")]
    [InverseProperty("StockItemOuterPackages")]
    public virtual PackageType OuterPackage { get; set; }

    [InverseProperty("StockItem")]
    public virtual ICollection<PurchaseOrderLine> PurchaseOrderLines { get; set; } = new List<PurchaseOrderLine>();

    [InverseProperty("StockItem")]
    public virtual ICollection<SpecialDeal> SpecialDeals { get; set; } = new List<SpecialDeal>();

    [InverseProperty("StockItem")]
    public virtual StockItemHolding StockItemHolding { get; set; }

    [InverseProperty("StockItem")]
    public virtual ICollection<StockItemStockGroup> StockItemStockGroups { get; set; } = new List<StockItemStockGroup>();

    [InverseProperty("StockItem")]
    public virtual ICollection<StockItemTransaction> StockItemTransactions { get; set; } = new List<StockItemTransaction>();

    [ForeignKey("SupplierId")]
    [InverseProperty("StockItems")]
    public virtual Supplier Supplier { get; set; }

    [ForeignKey("UnitPackageId")]
    [InverseProperty("StockItemUnitPackages")]
    public virtual PackageType UnitPackage { get; set; }
}
