// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataUpdateMethods.Models;

[Table("StockGroups", Schema = "Warehouse")]
[Index("StockGroupName", Name = "UQ_Warehouse_StockGroups_StockGroupName", IsUnique = true)]
public partial class StockGroup
{
    [Key]
    [Column("StockGroupID")]
    public int StockGroupId { get; set; }

    [Required]
    [StringLength(50)]
    public string StockGroupName { get; set; }

    public int LastEditedBy { get; set; }

    [ForeignKey("LastEditedBy")]
    [InverseProperty("StockGroups")]
    public virtual Person LastEditedByNavigation { get; set; }

    [InverseProperty("StockGroup")]
    public virtual ICollection<SpecialDeal> SpecialDeals { get; set; } = new List<SpecialDeal>();

    [InverseProperty("StockGroup")]
    public virtual ICollection<StockItemStockGroup> StockItemStockGroups { get; set; } = new List<StockItemStockGroup>();
}