// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataUpdateMethods.Models;

[Table("SupplierCategories", Schema = "Purchasing")]
[Index("SupplierCategoryName", Name = "UQ_Purchasing_SupplierCategories_SupplierCategoryName", IsUnique = true)]
public partial class SupplierCategory
{
    [Key]
    [Column("SupplierCategoryID")]
    public int SupplierCategoryId { get; set; }

    [Required]
    [StringLength(50)]
    public string SupplierCategoryName { get; set; }

    public int LastEditedBy { get; set; }

    [ForeignKey("LastEditedBy")]
    [InverseProperty("SupplierCategories")]
    public virtual Person LastEditedByNavigation { get; set; }

    [InverseProperty("SupplierCategory")]
    public virtual ICollection<Supplier> Suppliers { get; set; } = new List<Supplier>();
}