// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataUpdateMethods.Models;

[Table("Suppliers", Schema = "Purchasing")]
[Index("AlternateContactPersonId", Name = "FK_Purchasing_Suppliers_AlternateContactPersonID")]
[Index("DeliveryCityId", Name = "FK_Purchasing_Suppliers_DeliveryCityID")]
[Index("DeliveryMethodId", Name = "FK_Purchasing_Suppliers_DeliveryMethodID")]
[Index("PostalCityId", Name = "FK_Purchasing_Suppliers_PostalCityID")]
[Index("PrimaryContactPersonId", Name = "FK_Purchasing_Suppliers_PrimaryContactPersonID")]
[Index("SupplierCategoryId", Name = "FK_Purchasing_Suppliers_SupplierCategoryID")]
[Index("SupplierName", Name = "UQ_Purchasing_Suppliers_SupplierName", IsUnique = true)]
public partial class Supplier
{
    [Key]
    [Column("SupplierID")]
    public int SupplierId { get; set; }

    [Required]
    [StringLength(100)]
    public string SupplierName { get; set; }

    [Column("SupplierCategoryID")]
    public int SupplierCategoryId { get; set; }

    [Column("PrimaryContactPersonID")]
    public int PrimaryContactPersonId { get; set; }

    [Column("AlternateContactPersonID")]
    public int AlternateContactPersonId { get; set; }

    [Column("DeliveryMethodID")]
    public int? DeliveryMethodId { get; set; }

    [Column("DeliveryCityID")]
    public int DeliveryCityId { get; set; }

    [Column("PostalCityID")]
    public int PostalCityId { get; set; }

    [StringLength(20)]
    public string SupplierReference { get; set; }

    [StringLength(50)]
    public string BankAccountName { get; set; }

    [StringLength(50)]
    public string BankAccountBranch { get; set; }

    [StringLength(20)]
    public string BankAccountCode { get; set; }

    [StringLength(20)]
    public string BankAccountNumber { get; set; }

    [StringLength(20)]
    public string BankInternationalCode { get; set; }

    public int PaymentDays { get; set; }

    public string InternalComments { get; set; }

    [Required]
    [StringLength(20)]
    public string PhoneNumber { get; set; }

    [Required]
    [StringLength(20)]
    public string FaxNumber { get; set; }

    [Required]
    [Column("WebsiteURL")]
    [StringLength(256)]
    public string WebsiteUrl { get; set; }

    [Required]
    [StringLength(60)]
    public string DeliveryAddressLine1 { get; set; }

    [StringLength(60)]
    public string DeliveryAddressLine2 { get; set; }

    [Required]
    [StringLength(10)]
    public string DeliveryPostalCode { get; set; }

    [Required]
    [StringLength(60)]
    public string PostalAddressLine1 { get; set; }

    [StringLength(60)]
    public string PostalAddressLine2 { get; set; }

    [Required]
    [StringLength(10)]
    public string PostalPostalCode { get; set; }

    public int LastEditedBy { get; set; }

    [ForeignKey("AlternateContactPersonId")]
    [InverseProperty("SupplierAlternateContactPeople")]
    public virtual Person AlternateContactPerson { get; set; }

    [ForeignKey("DeliveryCityId")]
    [InverseProperty("SupplierDeliveryCities")]
    public virtual City DeliveryCity { get; set; }

    [ForeignKey("DeliveryMethodId")]
    [InverseProperty("Suppliers")]
    public virtual DeliveryMethod DeliveryMethod { get; set; }

    [ForeignKey("LastEditedBy")]
    [InverseProperty("SupplierLastEditedByNavigations")]
    public virtual Person LastEditedByNavigation { get; set; }

    [ForeignKey("PostalCityId")]
    [InverseProperty("SupplierPostalCities")]
    public virtual City PostalCity { get; set; }

    [ForeignKey("PrimaryContactPersonId")]
    [InverseProperty("SupplierPrimaryContactPeople")]
    public virtual Person PrimaryContactPerson { get; set; }

    [InverseProperty("Supplier")]
    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; } = new List<PurchaseOrder>();

    [InverseProperty("Supplier")]
    public virtual ICollection<StockItemTransaction> StockItemTransactions { get; set; } = new List<StockItemTransaction>();

    [InverseProperty("Supplier")]
    public virtual ICollection<StockItem> StockItems { get; set; } = new List<StockItem>();

    [ForeignKey("SupplierCategoryId")]
    [InverseProperty("Suppliers")]
    public virtual SupplierCategory SupplierCategory { get; set; }

    [InverseProperty("Supplier")]
    public virtual ICollection<SupplierTransaction> SupplierTransactions { get; set; } = new List<SupplierTransaction>();
}